[package]
name = "over_civ"
description = "OverCiv is a civilization styled 4x game"
version = "0.1.0"
authors = ["OvermindDL1 <overminddl1@gmail.com>"]
edition = "2018"

[dependencies]
# Base system dependencies
log4rs = {version = "1.0", features = ["toml_format"]}
tracing = {version = "0.1", features = ["attributes", "log", "log-always"]}
structopt = "0.3"
serde_derive = "1.0"
serde = {version = "1.0", features=["derive"]}
serde-value = "0.7"
serde_json = "1.0"
ron = "0.6.4"
anyhow = "1.0"
thiserror = "1.0"
lazy_static = "1.4.0"
# Game Data dependencies
indexmap = "1.6"
smol_str = "0.1.17"
rayon = "1.5"
# Game Engine dependencies
bevy = { version = "0.5", default_features = false, features = ["trace", "bevy_dynamic_plugin", "bevy_gltf"] }
bevy_egui = { version = "0.4", optional = true }
bevy-inspector-egui = { version = "0.4", optional = true }
unic-langid = "0.9"
intl-memoizer = "0.5"
fluent-syntax = "0.11"
fluent = "0.15"
crossterm = { version = "0.19", optional = true}
tui = { version = "0.14", default-features = false, features = ['crossterm'], optional = true }

[dev-dependencies]
proptest = "1.0"

[features]
default = ["client_tui", "client_wgpu", "server"]
client_wgpu = ["bevy/bevy_audio", "bevy/bevy_gilrs", "bevy/bevy_wgpu", "bevy/bevy_winit", "bevy/render", "bevy/png", "bevy/hdr", "bevy/mp3", "bevy/x11", "bevy_egui", "bevy-inspector-egui"]
client_tui = ["crossterm", "tui"]
server = []

[lib]
name = "over_civ"
path = "src/lib.rs"

[[bin]]
name = "over_civ"
path = "src/main.rs"
